### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by Snapperito** [Snapperito/Settings-Icons#23]
- [ ] rewrite & simplify code
 - [ ] redo icons with a more consistent design framework
 - [ ] add ground support for each Goosemod, Powercord, and Vizality plugin in their "Per-Plugin" settings field 
 - [ ] add easier ways to update / change plugins
